export const categories = [
  // {
  //   id: 'health-wellbeing-z8x7y6v3',
  //   name: 'Health & Wellbeing',
  //   instruction: 'Focusing on physical and mental health improvement',
  //   description:
  //     'Enhance your physical fitness, mental wellness, and lifestyle balance through healthy habits and mindful practices.',
  //   image: '',
  //   translateKey: 'Categories.options.healthAndWellbeing.name',
  //   tooltipKey: 'Categories.options.healthAndWellbeing.description',
  //   order: 1,
  // },
  // {
  //   id: 'finances-q9r8s7t6',
  //   name: 'Finances',
  //   instruction: 'Managing personal finances, budgeting, and financial planning',
  //   description: 'Manage your budgets, savings, and investments to achieve financial stability and long-term goals.',
  //   image: '',
  //   translateKey: 'Categories.options.finances.name',
  //   tooltipKey: 'Categories.options.finances.description',
  //   order: 2,
  // },
  {
    id: 'family-and-friends-k1l2m3n4',
    name: 'Family & Friends',
    instruction: 'Nurturing relationships with family and friends',
    description:
      'Strengthen relationships and foster meaningful connections with loved ones through communication and quality time.',
    image: '',
    translateKey: 'Categories.options.familyAndFriends.name',
    tooltipKey: 'Categories.options.familyAndFriends.description',
    order: 3,
  },
  {
    id: 'romance-e9f8g7h6',
    name: 'Romance',
    instruction: 'Navigating romantic relationships and personal connections',
    description: 'Develop and nurture romantic relationships with trust, communication, and shared experiences.',
    image: '',
    translateKey: 'Categories.options.romance.name',
    tooltipKey: 'Categories.options.romance.description',
    order: 4,
  },
  {
    id: 'personal-growth-y1z2a3b4',
    name: 'Personal Growth',
    instruction: 'Focusing on self-improvement and personal development',
    description:
      'Engage in self-improvement through learning new skills, self-reflection, and personal development activities.',
    image: '',
    translateKey: 'Categories.options.personalGrowth.name',
    tooltipKey: 'Categories.options.personalGrowth.description',
    order: 5,
  },
  {
    id: 'fun-and-recreation-s9t8u7v6',
    name: 'Fun & Recreation',
    instruction: 'Balancing enjoyment and leisure activities with daily responsibilities',
    description: 'Balance your routine with leisure activities and hobbies that bring joy, relaxation, and creativity.',
    image: '',
    translateKey: 'Categories.options.funAndRecreation.name',
    tooltipKey: 'Categories.options.funAndRecreation.description',
    order: 6,
  },
  {
    id: 'business-and-career-m5n6o7p8',
    name: 'Business & Career',
    instruction: 'Focusing on professional development and career advancement',
    description:
      'Advance your professional objectives and career path through strategic planning and skill enhancement.',
    image: '',
    translateKey: 'Categories.options.businessAndCareer.name',
    tooltipKey: 'Categories.options.businessAndCareer.description',
    order: 7,
  },
  {
    id: 'physical-environment-g9h8i7j6',
    name: 'Physical Environment',
    instruction: 'Creating and maintaining optimal living and working spaces',
    description:
      'Create and maintain organized, inspiring, and functional spaces at home and work for optimal well-being.',
    image: '',
    translateKey: 'Categories.options.physicalEnvironment.name',
    tooltipKey: 'Categories.options.physicalEnvironment.description',
    order: 8,
  },
  {
    id: 'spirituality-mindfulness-x1y2z3w4',
    name: 'Spirituality & Mindfulness',
    instruction: 'Focusing on meditation, introspection, and spiritual growth',
    description:
      'Cultivate inner peace and a deeper connection with your values through mindfulness, meditation, and spiritual exploration.',
    image: '',
    translateKey: 'Categories.options.spiritualityAndMindfulness.name',
    tooltipKey: 'Categories.options.spiritualityAndMindfulness.description',
    order: 9,
  },
  {
    id: 'community-and-contribution-c1o2m3p4',
    name: 'Community & Contribution',
    instruction: 'Focusing on community engagement, volunteering, and social impact',
    description:
      'Engage in community service and social initiatives to foster teamwork, support others, and make a positive impact.',
    image: '',
    translateKey: 'Categories.options.communityAndContribution.name',
    tooltipKey: 'Categories.options.communityAndContribution.description',
    order: 10,
  },
];
