FROM timescale/timescaledb-ha:pg16.6-ts2.18.0

USER root

RUN apt update && apt install gcc make postgresql-server-dev-16 flex bison -y
RUN curl -L -O https://github.com/apache/age/archive/refs/tags/PG16/v1.5.0-rc0.zip && unzip v1.5.0-rc0.zip

RUN cd age-PG16-v1.5.0-rc0 && make PG_CONFIG=/usr/lib/postgresql/16/bin/pg_config && make install PG_CONFIG=/usr/lib/postgresql/16/bin/pg_config

RUN chown postgres:postgres /usr/lib/postgresql/16/lib/age.so && chmod 644 /usr/lib/postgresql/16/lib/age.so

WORKDIR /home/postgres
USER postgres
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["postgres"]